# Ready
try:
    print("Hello World!\nWe don't have any exeptions.")
except KeyboardInterrupt:
    print('Exception')
except SystemExit:
    print('Exception')
except GeneratorExit:
    print('Exception')
except StopIteration:
    print('Exception')
except ArithmeticError:
    print('Exception')
except AssertionError:
    print('Exception')
except AttributeError:
    print('Exception')
except BufferError:
    print('Exception')
except EOFError:
    print('Exception')
except ImportError:
    print('Exception')
except LookupError:
    print('Exception')
except MemoryError:
    print('Exception')
except NameError:
    print('Exception')
except OSError:
    print('Exception')
except ReferenceError:
    print('Exception')
except RuntimeError:
    print('Exception')
except SyntaxError:
    print('Exception')
except SystemError:
    print('Exception')
except TypeError:
    print('Exception')
except ValueError:
    print('Exception')
except Warning:
    print('Exception')
